import localFont from "next/font/local";
import "./globals.css";
import RegisterServiceWorker from "./register-service-worker";
import { AuthProvider } from '../contexts/AuthContext'; 
import Navbar from '../components/Navbar';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "My Task List in PWA",
  description: "Generated by Little Wizard",
  manifest: '/manifest.json'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <Navbar />
              {children}
        </AuthProvider>
        <RegisterServiceWorker />
      </body>
    </html>
  );
}
